spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp

  application:
    name: ems #应用服务的名称


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #注册驱动
    url: jdbc:mysql://localhost:3306/ems?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root


server:
  servlet:
    context-path: /ems #设置项目名称
    jsp:
      init-parameters:
        development: true #开启jsp页面的热部署



mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml  #mapper配置文件的位置
  type-aliases-package: com.baizhi.ems.entity